language: node_js

node_js:
  - 8.0.0
  - 9.0.0
  - 10.0.0
  
sudo: false

install:
  - npm install

before_script:
  - npm run lint

after_script:
  - npm run test
  
cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm

notifications:
  email: 
    - stitchnig@gmail.com
